INSERT INTO skaters (skater_name, nationality, brand, bio) VALUES
('Yuto Horigome', 'JAPAN', 'April', 'Yuto Horigome is a Japanese professional skateboarder known for his technical skill and innovative style. Born on January 7, 1999, in Tokyo, he made history by winning the first-ever Olympic gold medal in skateboarding at the 2020 Tokyo Olympics in the men''s street event. Yuto is celebrated for his consistency and ability to perform complex tricks with ease, earning multiple titles in prestigious skateboarding competitions like X Games and Street League. He continues to be a leading figure in the global skateboarding scene.'), 
('Gustavo Ribeiro', 'PORTUGAL', 'Jart', 'Gustavo Ribeiro is a professional skateboarder from Portugal, recognized for his powerful and precise skating style. Born on March 27, 2001, he has quickly risen to prominence in the global skateboarding scene, consistently placing high in competitions like Street League and X Games. Gustavo is known for his ability to land difficult tricks with remarkable consistency, making him one of the top street skaters in the world. He has also represented Portugal in international competitions, including the Tokyo 2020 Olympics, where skateboarding made its debut.'), 
('Nyjah Huston', 'USA', 'Disorder', 'Nyjah Huston is an American professional skateboarder and one of the most dominant figures in the sport. Born on November 30, 1994, in Davis, California, Nyjah has been a competitive skater since childhood and has won more titles than any other skater in Street League Skateboarding history. Known for his fearless approach and ability to land high-risk tricks, he has also claimed multiple X Games gold medals and podium finishes in major skateboarding events worldwide. Nyjah competed in the 2020 Tokyo Olympics and remains a global icon in street skateboarding.'),
('Kelvin Hoefler', 'BRAZIL', 'Powell Peralta', 'Kelvin Hoefler is a Brazilian professional skateboarder known for his technical precision and consistency in street skateboarding. Born on February 10, 1993, in Guarujá, Brazil, Kelvin has earned multiple titles in top-tier competitions like X Games, Street League Skateboarding, and Dew Tour. He made history by winning the silver medal in the men''s street event at the 2020 Tokyo Olympics, where skateboarding made its Olympic debut. Kelvin''s ability to perform difficult tricks under pressure has cemented his reputation as one of the best street skaters in the world.'),
('Jamie Foy', 'USA', 'Deathwish', 'Jamie Foy is an American professional skateboarder renowned for his fearless approach and ability to tackle massive handrails with ease. Born on June 14, 1996, in Deerfield Beach, Florida, Jamie quickly gained attention for his powerful style and technical precision. In 2017, he was named Thrasher Magazine''s “Skater of the Year,” a prestigious honor in the skateboarding world. Jamie is known for his versatility, excelling in both street skating and transition, and regularly competes in major competitions like X Games and Street League. His unique style and dedication have made him a standout in the skateboarding community.'),
('Daiki Ikeda', 'JAPAN', 'Toy Machine', 'Daiki Ikeda is a rising Japanese professional skateboarder known for his technical skills and smooth style. Born on February 28, 2005, Daiki has quickly made a name for himself in the international skateboarding scene. He gained widespread recognition by winning the 2022 Street League Skateboarding (SLS) Super Crown World Championship, becoming one of the youngest skaters to do so. With his innovative tricks and consistent performances, Daiki is seen as one of the future stars of street skateboarding, representing the next generation of talent in the sport.'),
('Dashawn Jordan', 'USA', 'April', 'Dashawn Jordan is an American professional skateboarder known for his powerful, fluid style and ability to execute difficult tricks with precision. Born on February 5, 1997, in Chandler, Arizona, Dashawn has gained recognition for his performances in major skateboarding competitions, including Street League Skateboarding (SLS) and X Games, where he has earned several podium finishes. In 2017, he won the SLS Pro Open, further solidifying his place among the top street skaters in the world. Dashawn''s mix of athleticism and technical skill has made him a fan favorite and a prominent figure in the global skateboarding community.'),
('Felipe Gustavo', 'BRAZIL', 'Plan B', 'Felipe Gustavo is a Brazilian professional skateboarder known for his smooth, technical style and exceptional consistency. Born on March 22, 1991, in Brasília, Brazil, Felipe rose to fame after winning the Tampa Am contest in 2007, a significant turning point in his career. Since then, he has become a regular competitor in major skateboarding events like Street League Skateboarding (SLS) and X Games. Felipe is admired for his ability to perform highly technical tricks with precision, especially in street skating. His influence and skill have earned him a place among the top skateboarders in the world.'),
('Aurelien Giraud', 'FRANCE', 'Plan B', 'Aurelien Giraud is a French professional skateboarder known for his explosive style and ability to land difficult tricks with precision and power. Born on February 3, 1998, in Lyon, France, Aurelien gained international attention for his performances in major contests like Street League Skateboarding (SLS), X Games, and Dew Tour. His fearless approach, particularly on large obstacles, has made him a standout in the street skating scene. Aurelien represented France in the 2020 Tokyo Olympics, showcasing his skills on the world stage and solidifying his reputation as one of the top skateboarders globally.'),
('Giovanni Vianna', 'BRAZIL', 'Primitive', 'Giovanni Vianna is a Brazilian professional skateboarder known for his powerful and versatile style, excelling in both street and park disciplines. Born on January 27, 2001, in Santo André, Brazil, Giovanni quickly gained recognition through his standout performances in competitions like Street League Skateboarding (SLS) and Dew Tour. His ability to combine technical tricks with creative lines has made him a rising star in the global skateboarding scene. Giovanni also represented Brazil in the 2020 Tokyo Olympics, contributing to his growing reputation as one of the top young talents in skateboarding today.'),
('Vincent Milou', 'FRANCE', 'Pizza Skateboards', 'Vincent Milou is a French professional skateboarder known for his stylish, fluid approach and technical expertise in street skating. Born on November 11, 1996, in Tarnos, France, Vincent has made a name for himself through strong performances in major competitions such as Street League Skateboarding (SLS), X Games, and Dew Tour. His ability to blend technical tricks with creative lines has earned him a spot among the top skaters in the world. Vincent represented France in the 2020 Tokyo Olympics, further solidifying his place as a prominent figure in the global skateboarding community.');


INSERT INTO videos (skater_id, video_name, video_date, youtube_url) VALUES
(1, '"The Yuto Show!" Part', 2021, 'https://www.youtube.com/watch?v=gpBhkU3q_gg'),
(1, '"April" Part', 2023, 'https://www.youtube.com/watch?v=FLuur2b97Es'),
(2, '"Nine To Five" Part', 2019, 'https://www.youtube.com/watch?v=9cSEojH3U74&t=40s'),
(2, '"FUTURO" Part', 2023, 'https://www.youtube.com/watch?v=p9PVfqOtC40'),
(3, '"Need That" Part', 2023, 'https://www.youtube.com/watch?v=CYw4CvUSaLM'),
(3, '"Shine On" Part', 2021, 'https://www.youtube.com/watch?v=ZmIU1hnEvjE'),
(4, '"Green Card" Part', 2015, 'https://www.youtube.com/watch?v=uiePHSZm0Kw&t=4s'),
(4, '"It Must Be Nice" Part', 2018, 'https://www.youtube.com/watch?v=pOuHZgxpIrU&t=3s'),
(5, '"Sunshine State" Part', 2021, 'https://www.youtube.com/watch?v=TGRQM0X7uQ8&t=2s'),
(5, '"YOU GOOD?" Part', 2021, 'https://www.youtube.com/watch?v=whbElXqbWHU'),
(6, '"Where The Hell Did This Kid Come From?!" Part', 2021, 'https://www.youtube.com/watch?v=vTpJXxPb-co'),
(7, '"NEXT LEVEL 2023" Part', 2023, 'https://www.youtube.com/watch?v=0WtjycOh_hA'),
(7, '"Dashawn Jordan" April Part', 2023, 'https://www.youtube.com/watch?v=5aneN44QRuU'),
(8, '"vAMdalism" Plan B Part', 2010, 'https://www.youtube.com/watch?v=RFouAuMsVfI&t=3s'),
(8, '"De La Calle" Part', 2024, 'https://www.youtube.com/watch?v=l06W1UspnYI'),
(9, '"AURELIEN GIRAUD STREET PART"', 2019, 'https://www.youtube.com/watch?v=UvngAZf4V4A'),
(10, 'Giovanni Vianna for Primitive Skate', 2020, 'https://www.youtube.com/watch?v=YnFN8pfatLA'),
(10, '"RITORNA" Part', 2023, 'https://www.youtube.com/watch?v=sGBqj31a35U'),
(11, '"All the Way Down" Part', 2019, 'https://www.youtube.com/watch?v=2CV35TrHfwo&t=2s'),
(11, '"XXX" Pizza Part', 2022, 'https://www.youtube.com/watch?v=rL0kyNm5rG8');


